### ISSUE TITLE
Sign in page says "This browser may not be secure"

### ISSUE THREAD

**Issue by TheTrio** [ItsDandelia/Google-Meet-Auto-SignIn#1]
Hey! I was trying to make a similar program, but kept running into issues because of Google detecting that I was using browser automation. After searching around a bit,  I found your program. 

Unfortunately, your program ran into the same problem. Here's the screenshot

![](https://cdn.discordapp.com/attachments/694190268424912939/793839274575134720/unknown.png)

Are you aware of any way to bypass this?  (Assuming that bypassing this is even possible).

**Comment by ItsDandelia** [comment]
Hey hi,
Try to sign in using a freshly made gmail account. Many times Google marks accounts that have been using browser automation and blocks them when they try to sign in automatically. This is can be solved if you make a  new Gmail account. If the issue still persists then do let me know :)
